- name: Add the kubernetes-archive-keyring apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present

# see https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
- name: Add the kubernetes repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

# NB execute apt-cache madison kubectl to known the available versions.
- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl={{ kubectl_version }}-*
    state: present

- name: Install kubectl bash completion
  block:
    - name: Get kubectl bash completion
      ansible.builtin.shell: kubectl completion bash
      register: bash_completion
      changed_when: false
    - name: Install kubectl bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/kubectl
