- name: Install Projects
  become_user: vagrant
  block:
    - name: Create the Projects directory
      ansible.builtin.file:
        name: ~/Projects
        state: directory
        mode: 0755
    - name: Clone ubuntu-vagrant
      ansible.builtin.git:
        repo: https://github.com/rgl/ubuntu-vagrant.git
        dest: ~/Projects/ubuntu-vagrant
    - name: Clone windows-vagrant
      ansible.builtin.git:
        repo: https://github.com/rgl/windows-vagrant.git
        dest: ~/Projects/windows-vagrant
    - name: Clone my-ubuntu-ansible-playbooks
      ansible.builtin.git:
        repo: https://github.com/rgl/my-ubuntu-ansible-playbooks.git
        dest: ~/Projects/my-ubuntu-ansible-playbooks
    - name: Clone my-ubuntu-windows-playbooks
      ansible.builtin.git:
        repo: https://github.com/rgl/my-windows-ansible-playbooks.git
        dest: ~/Projects/my-windows-ansible-playbooks
