- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 10800 # 3h
  changed_when: false

- name: Install vim
  block:
    - name: Install vim
      apt:
        name: vim
        install_recommends: no
    - name: Install vimrc
      copy:
        src: vimrc.local
        dest: /etc/vim/vimrc.local

- name: Install git
  block:
    - name: Install git
      apt:
        name: git
        install_recommends: no
    - name: Install gitconfig
      copy:
        src: gitconfig
        dest: /etc/gitconfig

- name: Install login profile
  copy:
    src: login.sh
    dest: /etc/profile.d/login.sh

- name: Install libreadline inputrc
  copy:
    src: inputrc
    dest: /etc/inputrc

- name: Install useful tools
  apt:
    name:
      - tcpdump
      - unzip
      - httpie
      - jq
      - python3-tabulate
      - bash-completion
      - p7zip-full
      - patch
      # iso creation tool.
      # NB xorriso is compatible with genisoimage and mkisofs and is also available in msys2 (windows).
      - xorriso
      # iso-info tool.
      # NB iso-info is also available in msys2 (windows) as provided by the mingw-w64-x86_64-libcdio package.
      - libcdio-utils
      # etherwake lets us power-on a machine by sending a Wake-on-LAN (WOL)
      # magic packet to its ethernet card.
      # e.g. etherwake -i eth1 00:e0:4c:01:93:a8
      - etherwake
    install_recommends: no
