- name: Infra Toolbox
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - base
    - role: kvm
      when: "'kvm' in ansible_virtualization_tech_host"
    - docker
    - docker_registry
    - powershell
    - yq
    - k8s_client
    - azure_client
    - gcp_client
    - vmware_client
    - packer
    - terraform
    - vagrant
    - cue
    - dagger
    - projects
