- hosts: localhost
  gather_facts: true
  become: true
  roles:
    - base
    - role: kvm
      when: "'kvm' in ansible_virtualization_tech_host"
    - docker
    - powershell
    - yq
    - k8s-client
    - azure-client
    - vmware-client
    - packer
    - terraform
    - vagrant
    - cue
    - dagger
    - projects
