- hosts: localhost
  gather_facts: yes
  become: yes
  roles:
    - base
    - role: kvm
      when: "'kvm' in ansible_virtualization_tech_host"
    - docker
    - powershell
    - k8s-client
    - azure-client
    - vmware-client
    - packer
    - terraform
    - vagrant
    - dagger
