- name: Infra Toolbox
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - base
    - role: kvm
      when: "'kvm' in ansible_virtualization_tech_host"
    - docker
    - docker-registry
    - powershell
    - yq
    - k8s-client
    - azure-client
    - gcp-client
    - vmware-client
    - packer
    - terraform
    - vagrant
    - cue
    - dagger
    - projects
